name: "Hello"

# on:
#   workflow_dispatch:
on:
  pull_request:
      types: [opened, reopened]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          name: "Yonomesh Tech"
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          label: "needs-review"
