name: "Hello"

on:
  workflow_dispatch:
    
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          who-to-greet: "Yonomesh"
          greeting: 'neoooooo'